/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:15:12                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_03_PEOPLE_AI0 FOR PEOPLE
ACTIVE AFTER INSERT POSITION 2
AS
	DECLARE VARIABLE OP_ADD_USER INTEGER = 3;
begin
 INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (new.id_db,NULL,NULL,NULL,:OP_ADD_USER,0,new.id_pep);
end
^


SET TERM ; ^
DESCRIBE TRIGGER PARSEC_03_PEOPLE_AI0
'Триггер срабатывает при добавлении нового пользователя в таблицу people.';