/******************************************************************************/
/***                Generated by IBExpert 15.09.2026 8:27:07                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_35_PEOPLE_AU0 FOR PEOPLE
ACTIVE AFTER UPDATE POSITION 0
AS
	DECLARE VARIABLE OP_UPDATE_PEOPLE INTEGER = 35;
begin
    if((new.id_org<>old.id_org)
        or (new.surname<>old.surname)
        or(new.name<>old.name)
        or(new.patronymic<>old.patronymic)
        or(new.tabnum<>old.tabnum)) then
    begin
        INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (new.id_db,NULL,NULL,NULL,:OP_UPDATE_PEOPLE,0,new.id_pep);
    end
end
^


SET TERM ; ^


DESCRIBE TRIGGER PARSEC_35_PEOPLE_AU0
'Изменения параметров пользователя (фио, организации) вызывает изменения параметров пользователя в Парсеке';
