/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:16:10                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_04_PEOPLE_AD0 FOR PEOPLE
ACTIVE AFTER DELETE POSITION 0
AS
begin
 INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,old.guid,NULL,NULL,4,0,old.id_pep);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_04_PEOPLE_AD0
'Удаление пользователя';
