/******************************************************************************/
/***                Generated by IBExpert 15.09.2026 8:28:17                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_55_ORGANIZATION_AU0 FOR ORGANIZATION
ACTIVE AFTER UPDATE POSITION 0
AS
	DECLARE VARIABLE OP_UPDATE_ORG INTEGER = 55;
begin
    if((new.id_parent<>old.id_parent)
        or (new.name<>old.name)
        or(new.divcode<>old.divcode)) then 
            begin
                INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS, ID_PEP) VALUES (new.id_db,new.guid,NULL,NULL,:OP_UPDATE_ORG,0, 1);
            end
end
^


SET TERM ; ^


DESCRIBE TRIGGER PARSEC_55_ORGANIZATION_AU0
'Изменения параметров организации (название, родитель) вызывает изменения параметров организации в Парсеке';
