/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:33:32                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_05_ORGANIZATION_AI0 FOR ORGANIZATION
ACTIVE AFTER INSERT POSITION 0
AS
	DECLARE VARIABLE OP_ADD_ORG INTEGER = 5;
begin
 INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS, ID_PEP) VALUES (new.id_db,new.guid,NULL,NULL,:OP_ADD_ORG,0, 1);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_05_ORGANIZATION_AI0
'Триггер срабатывает при добавление организации';

