/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:26:32                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_10_CARD_AD0 FOR CARD
ACTIVE AFTER DELETE POSITION 0
AS
begin
   --если пипл уже удален, то удалять карту не не надо. парсек сам удалит карту при удалдении пипла
   if(exists(select p.id_pep from people p where p.id_pep=old.id_pep)) then
        if(old.id_cardtype=1) then 
             INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,old.id_card,NULL,NULL,10,0,old.id_pep);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_10_CARD_AD0
'Удаление идентификатора у пользователя вызывает удаление идентификатора в Парсеке.';

