/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:04:33                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_07_SS_ACCESSUSER_AI0 FOR SS_ACCESSUSER
ACTIVE AFTER INSERT POSITION 0
AS
begin
    -- выставлять комануд если категорию доступа принадлежит Парсеку
    if(EXISTS (
        SELECT 1 
        FROM accessname an
        LEFT JOIN access a ON an.id_accessname = a.id_accessname
        LEFT JOIN device d ON a.id_dev = d.id_dev
        LEFT JOIN device d2 ON d2.id_ctrl = d.id_ctrl AND d2.id_reader IS NULL
        LEFT JOIN server s ON d2.id_server = s.id_server
        WHERE an.id_accessname = new.id_accessname AND s.id_server = 1 )) then
        --выставлять команду если у пипла есть карта
            if(exists(select c.id_card from card c where c.id_pep=new.id_pep and c.id_cardtype=1 and c."ACTIVE">0)) then
                    INSERT INTO cardindev (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,new.id_accessname,NULL,NULL,7,0,new.id_pep);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_07_SS_ACCESSUSER_AI0
'Добавление категории доступа пользователю вызывает добавление категории доступа выданных ему идентификаторам.';
