/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:14:13                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_08_SS_ACCESSUSER_AD0 FOR SS_ACCESSUSER
ACTIVE AFTER DELETE POSITION 0
AS
begin
    -- выставлять комануд если категорию доступа принадлежит Парсеку
    if(EXISTS (
        SELECT 1 
        FROM accessname an
        LEFT JOIN access a ON an.id_accessname = a.id_accessname
        LEFT JOIN device d ON a.id_dev = d.id_dev
        LEFT JOIN device d2 ON d2.id_ctrl = d.id_ctrl AND d2.id_reader IS NULL
        LEFT JOIN server s ON d2.id_server = s.id_server
        WHERE an.id_accessname = old.id_accessname AND s.id_server = 1 )) then
        --формирую команду, если этот id_pep еще есть. При удалдении пипла в этот момент самого пипла может и не быть
          if(exists(select p.id_pep from people p where p.id_pep=old.id_pep)) then
           --выставлять команду если у пипла есть карта
                if(exists(select c.id_card from card c where c.id_pep=old.id_pep)) then
                    INSERT INTO cardindev (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,old.id_accessname,NULL,NULL,8,0,old.id_pep);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_08_SS_ACCESSUSER_AD0
'Удаление категории доступа пользователю вызывает удаление категории доступа выданных ему идентификаторам.';
