/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:17:24                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_35_PEOPLE_AU0 FOR PEOPLE
ACTIVE AFTER UPDATE POSITION 0
AS
begin
 INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,NULL,NULL,NULL,35,0,new.id_pep);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_35_PEOPLE_AU0
'Изменения параметров пользователя (фио, организации) вызывает изменения параметров пользователя в Парсеке';
