/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:19:27                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_06_ORGANIZATION_BD0 FOR ORGANIZATION
ACTIVE BEFORE DELETE POSITION 0
AS
begin
 INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,old.guid,NULL,NULL,6,0,1);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_06_ORGANIZATION_BD0
'Добавление организации';
