/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:36:10                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_07_09_CARD_AI0 FOR CARD
ACTIVE AFTER INSERT POSITION 0
AS
declare variable id_accessname integer;
begin
    -- если у пипла уже есть категории доступа, то их надо присвоить выданной карте
   if(new.id_cardtype =1 ) then
   begin 
      INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,new.id_card,NULL,NULL,9,0,new.id_pep);
            if(exists(select ssu.id_accessuser from ss_accessuser ssu where ssu.id_pep=new.id_pep)) then
            begin
                for select ssu2.id_accessname from ss_accessuser ssu2
                where ssu2.id_accessname between 36 and 56
                   and ssu2.id_pep=new.id_pep into :id_accessname
                do
                    --INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,new.id_card,NULL,NULL,11,0,:id_accessname);
                    --код операции 7 - добавить категорию доступа пиплу, и далее, через  него картам.
                INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS,ID_PEP) VALUES (1,:id_accessname,NULL,NULL,7,0,new.id_pep);
             end
  end

end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_07_09_CARD_AI0
'Добавление идентификатора пользователю. Если пользователю уже присвоены категории доступа, то эти категории доступа присваиваются и выданном идентификатору.
ВРЕМЕННОЕ РЕШЕНИЕ: диапазон категорий доступа фиксированный!!! надо исправить на настраиваемый, привязанный к категориям доступа парсека.
';
