/******************************************************************************/
/***                Generated by IBExpert 09.09.2026 7:18:34                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER PARSEC_55_ORGANIZATION_AU0 FOR ORGANIZATION
ACTIVE AFTER UPDATE POSITION 0
AS
begin
 INSERT INTO CARDINDEV (ID_DB,ID_CARD,DEVIDX,ID_DEV,OPERATION,ATTEMPTS, ID_PEP) VALUES (1,new.guid,NULL,NULL,55,0, 1);
end
^


SET TERM ; ^

DESCRIBE TRIGGER PARSEC_55_ORGANIZATION_AU0
'Изменения параметров организации (название, родитель) вызывает изменения параметров организации в Парсеке';
